name: Publish

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  publish:
    name: "Deploy"
    timeout-minutes: 3
    runs-on: ["ubuntu-latest"]
    steps:
      - name: "🔑 Checkout"
        uses: actions/checkout@v5

      - name: "🐰 Setup bun"
        uses: oven-sh/setup-bun@main
        with:
          bun-version: "latest"

      - name: "Install Dependencies"
        run: bun install --frozen-lockfile --verbose

      - name: "Lint, Check, Build"
        run: |
          bun x @biomejs/biome check . --reporter='github'
          bun typecheck
          bun run build

      - name: "Publish - Chrome Web Store"
        run: |
          # TODO: Publish to Chrome Web Store

      - name: "Publish - Firefox Add-ons"
        run: |
          # TODO: Publish to Firefox Add-ons

      - name: "Publish - Safari Extensions"
        run: |
          # TODO: Publish to Safari Extensions
