name: Pull Request

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  RETENTION_DAYS: 5
  ACTIONS_RUNNER_DEBUG: true

jobs:
  check:
    name: "Check, Build & Comment"
    timeout-minutes: 5
    runs-on: ["ubuntu-latest"]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "🔑 Checkout"
        uses: actions/checkout@v5

      - name: "🐰 Setup bun"
        uses: oven-sh/setup-bun@main
        with:
          bun-version: "latest"

      - name: "📦 Install Dependencies"
        run: bun install --frozen-lockfile --verbose

      - name: "🔍 Lint & Format"
        run: |
          bun x @biomejs/biome check . --reporter='github'

      - name: "✅ Typecheck"
        run: bun typecheck

      - name: "🏗️ Build"
        run: |
          bun run build
          bun run compile

      - name: "📦 Build and zip Chrome extension"
        run: bun run zip

      - name: "🦊 Build and zip Firefox extension"
        run: |
          bun run build:firefox
          bun run zip:firefox

      - name: "🗂️ Prepare artifacts"
        id: artifacts
        run: |
          mkdir -p pr-artifacts

          # Find the generated zip files
          CHROME_ZIP=$(find .output -name "*chrome*.zip" -type f | head -n 1)
          FIREFOX_ZIP=$(find .output -name "*firefox*.zip" -type f | head -n 1)

          # If chrome zip not found by name, try finding the default zip
          if [ -z "$CHROME_ZIP" ]; then
            CHROME_ZIP=$(find .output -name "*.zip" -type f -not -name "*firefox*" | head -n 1)
          fi

          # Copy and rename for clarity
          if [ -n "$CHROME_ZIP" ]; then
            cp "$CHROME_ZIP" pr-artifacts/d2go-chrome.zip
            echo "chrome_exists=true" >> $GITHUB_OUTPUT
          fi

          if [ -n "$FIREFOX_ZIP" ]; then
            cp "$FIREFOX_ZIP" pr-artifacts/d2go-firefox.zip
            echo "firefox_exists=true" >> $GITHUB_OUTPUT
          fi

          ls -la pr-artifacts/

      - name: "🌐 Upload Artifact - Chromium"
        if: steps.artifacts.outputs.chrome_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          overwrite: true
          path: pr-artifacts/d2go-chrome.zip
          retention-days: ${{ env.RETENTION_DAYS }}
          name: d2go-chrome-pr${{ github.event.pull_request.number }}

      - name: "🌐 Upload Artifact - Firefox"
        if: steps.artifacts.outputs.firefox_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          overwrite: true
          path: pr-artifacts/d2go-firefox.zip
          retention-days: ${{ env.RETENTION_DAYS }}
          name: d2go-firefox-pr${{ github.event.pull_request.number }}

      - name: "💬 Comment on PR"
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT || github.token }}
        run: |
          # Get the run URL for artifact downloads
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # Create comment body with unique identifier
          cat > comment.md << 'EOF'
          <!-- d2go-extension-build-comment -->
          ## 📦 Extension Build Artifacts

          The extension has been built successfully! You can download and test the builds:

          ### Chromium: Chrome / Brave / Edge / etc.
          - **Download**: [d2go-chrome-pr${{ github.event.pull_request.number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          - **Installation**:
            1. Download and extract the zip file
            2. Navigate to `chrome://extensions/`
            3. Enable "Developer mode"
            4. Click "Load unpacked" and select the extracted folder

          ### SpiderMonkey: Firefox / Zen / etc.
          - **Download**: [d2go-firefox-pr${{ github.event.pull_request.number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          - **Installation**:
            1. Download the zip file
            2. Navigate to `about:debugging#/runtime/this-firefox`
            3. Click "Load Temporary Add-on..."
            4. Select the downloaded zip file

          > **Note**: Artifacts are available for 30 days from the [workflow run]($RUN_URL).

          ---
          <sub>Build triggered by commit ${{ github.event.pull_request.head.sha }}</sub>
          EOF

          # Check if comment already exists (find comment with our identifier)
          COMMENT_ID=$(gh pr view ${{ github.event.pull_request.number }} --json comments --jq '.comments[] | select(.body | contains("<!-- d2go-extension-build-comment -->")) | .id' 2>/dev/null | head -n 1 || echo "")

          if [ -n "$COMMENT_ID" ] && [ "$COMMENT_ID" != "null" ]; then
            # Try to edit existing comment
            echo "Found existing comment ID: $COMMENT_ID, attempting to update..."
            if gh api \
              --method PATCH \
              "/repos/${{ github.repository }}/issues/comments/$COMMENT_ID" \
              -f body="$(cat comment.md)" 2>/dev/null; then
              echo "✅ Successfully updated existing comment"
            else
              echo "⚠️ Failed to update comment, creating new one..."
              gh pr comment ${{ github.event.pull_request.number }} --body-file comment.md
            fi
          else
            # Create new comment
            echo "No existing comment found, creating new one..."
            gh pr comment ${{ github.event.pull_request.number }} --body-file comment.md
            echo "✅ Successfully created new comment"
          fi
